//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoeTheGadgeteer {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The Breakout module using socket 4 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Breakout upperServos;
        
        /// <summary>The Breakout module using socket 3 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Breakout lowerServos;
        
        /// <summary>The Temp&Humidity module using socket 2 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.TempHumidity temperatureHumidity;
        
        /// <summary>The ColorSense module using socket 5 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.ColorSense colorSensor;
        
        /// <summary>The Distance US3 module using socket 7 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.DistanceUS3 distanceSensor;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZCerberus Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZCerberus)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZCerberus();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.upperServos = new GTM.GHIElectronics.Breakout(4);
            this.lowerServos = new GTM.GHIElectronics.Breakout(3);
            this.temperatureHumidity = new GTM.GHIElectronics.TempHumidity(2);
            this.colorSensor = new GTM.GHIElectronics.ColorSense(5);
            this.distanceSensor = new GTM.GHIElectronics.DistanceUS3(7);
        }
    }
}
